default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: education-management-api-development

test:
  <<: *default
  database: education-management-api-test

production:
  <<: *default
  database: education-management-api-production
